# 开发环境配置
app:
  prefix: '/dev-api'
  port: 9802
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址，开发环境
    domain: 'http://localhost:9801'
    # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8081/static/****.jpg  , 如果不需要则 设置 ''
    serveRoot: '/static'
  name: 'service-b'
  active: 'dev'

db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: 'mysqlpassword'
    database: 'kapok2'
    port: 36693
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: 'localhost'
  port: 6379
  password: 123456
  db: 0
  keyPrefix: 'nest:'

